const AUTH_EVENTS = {
    SIGNUP_SUCCESS: 'signup_success',
    SIGNUP_FAILED: 'signup_failed',
    LOGIN_SUCCESS: 'login_success',
    LOGIN_FAILED: 'login_failed',
    LOGOUT: 'logout',
    INVITATION_SENT: 'invitation_sent',
    INVITATION_ACCEPTED: 'invitation_accepted',
    INVITATION_ACCEPT_FAILED: 'invitation_accept_failed',
    INVITATION_REVOKED: 'invitation_revoked',
    EMAIL_VERIFICATION_REQUESTED: 'email_verification_requested',
    EMAIL_VERIFICATION_SENT: 'email_verification_sent',
    EMAIL_VERIFICATION_FAILED: 'email_verification_failed',
    EMAIL_VERIFIED: 'email_verified',
    PASSWORD_RESET_REQUESTED: 'password_reset_requested',
    PASSWORD_RESET_COMPLETED: 'password_reset_completed',
    PASSWORD_RESET_FAILED: 'password_reset_failed',
    BOOTSTRAP_PLATFORM_OWNER: 'bootstrap_platform_owner',
    BOOTSTRAP_PLATFORM_OWNER_FAILED: 'bootstrap_platform_owner_failed',
    RATE_LIMIT_BLOCKED: 'rate_limit_blocked',
    SUSPICIOUS_ACTIVITY: 'suspicious_activity'
};

const AUTH_SEVERITY = {
    INFO: 'info',
    NOTICE: 'notice',
    WARNING: 'warning',
    CRITICAL: 'critical'
};

const AUTH_EVENT_STATUS = {
    SUCCESS: 'success',
    FAILED: 'failed',
    BLOCKED: 'blocked'
};

const EVENT_DEFAULT_SEVERITY = {
    [AUTH_EVENTS.SIGNUP_SUCCESS]: AUTH_SEVERITY.INFO,
    [AUTH_EVENTS.LOGIN_SUCCESS]: AUTH_SEVERITY.INFO,
    [AUTH_EVENTS.INVITATION_SENT]: AUTH_SEVERITY.NOTICE,
    [AUTH_EVENTS.INVITATION_ACCEPTED]: AUTH_SEVERITY.NOTICE,
    [AUTH_EVENTS.EMAIL_VERIFIED]: AUTH_SEVERITY.INFO,
    [AUTH_EVENTS.PASSWORD_RESET_REQUESTED]: AUTH_SEVERITY.NOTICE,
    [AUTH_EVENTS.PASSWORD_RESET_COMPLETED]: AUTH_SEVERITY.NOTICE,
    [AUTH_EVENTS.BOOTSTRAP_PLATFORM_OWNER]: AUTH_SEVERITY.CRITICAL,
    [AUTH_EVENTS.SIGNUP_FAILED]: AUTH_SEVERITY.WARNING,
    [AUTH_EVENTS.LOGIN_FAILED]: AUTH_SEVERITY.WARNING,
    [AUTH_EVENTS.INVITATION_ACCEPT_FAILED]: AUTH_SEVERITY.WARNING,
    [AUTH_EVENTS.PASSWORD_RESET_FAILED]: AUTH_SEVERITY.WARNING,
    [AUTH_EVENTS.BOOTSTRAP_PLATFORM_OWNER_FAILED]: AUTH_SEVERITY.CRITICAL,
    [AUTH_EVENTS.RATE_LIMIT_BLOCKED]: AUTH_SEVERITY.WARNING,
    [AUTH_EVENTS.SUSPICIOUS_ACTIVITY]: AUTH_SEVERITY.CRITICAL
};

module.exports = {
    AUTH_EVENTS,
    AUTH_SEVERITY,
    AUTH_EVENT_STATUS,
    EVENT_DEFAULT_SEVERITY
};
