module.exports = {
    USERS: 'users',
    REFRESH_TOKENS: 'refresh_tokens',
    COMPOSITIONS: 'compositions',
    MENU_ITEMS: 'menu_items',
    MENU_ITEM_COMPOSITIONS: 'menu_item_compositions',
    CATEGORIES: 'categories',
    TYPE_CATEGORIES: 'type_categories',
    TABLES: 'tables',
    TABLE_SESSIONS: 'table_sessions',
    CUSTOMERS: 'customers',
    ORDERS: 'commandes',
    ORDER_ITEMS: 'commande_items',
    ORDER_ITEM_COMPOSITIONS: 'commande_item_compositions',
    CARTS: 'paniers',
    CART_ITEMS: 'panier_items',
    CART_ITEM_COMPOSITIONS: 'panier_item_compositions',
    RESTAURANTS: 'restaurants',
    ORGANIZATIONS: 'organizations',
    BRANCHES: 'branches',
    TENANT_MIGRATIONS: 'tenant_migrations',
    AUTH_LOGS: 'auth_logs',
    EMAIL_EVENTS: 'email_events',
    STAFF_INVITATIONS: 'staff_invitations',
    IMPERSONATION_LOGS: 'impersonation_logs'
};
